# 修改标题等基本信息
title: Lemou's Blog  # 改成你想要的博客标题
tagline: 个人技术博客   # 改成你想要的副标题
description: 分享技术与生活 # 改成你的博客描述

# 填写你的 GitHub Pages URL
url: "https://lemou-memo.github.io"

# 修改为你的 GitHub 信息
github:
  username: Lemou-Memo  # 改成你的 GitHub 用户名

# 修改社交信息
social:
  name: Lemou  # 改成你的名字
  email: 你的邮箱  # 改成你的邮箱
  links:
    - https://github.com/Lemou-Memo  # 改成你的 GitHub 主页链接

# 设置时区
timezone: Asia/Shanghai

# 设置主题模式（可选）
theme_mode: dark  # [light|dark]

# # 设置头像（可选）
# avatar: /assets/img/avatar.jpg  # 后续可以添加你的头像